---
- set_fact:
    release: ""

- set_fact:
    release: "22"
  when: (ansible_lsb['id'] == "Ubuntu" and ansible_lsb['major_release'] == "22") or (ansible_lsb['id'] == "Linuxmint" and ansible_lsb['major_release'] == "21")

- name: ensure virtualbox is installed
  apt:
    name: "{{ [ virtualbox_package_name ] + virtualbox_exclusive_packages + virtualbox_shared_packages }}"
    state: present
  become: true
  when: release != "22"

- name: ensure virtualbox is installed
  apt:
    name: "{{ [ virtualbox_package_name ] + virtualbox_exclusive_packages_jammy + virtualbox_shared_packages }}"
    state: present
  become: true
  when: release == "22"

- name: set username
  command: whoami
  register: virtualbox_username
  check_mode: false
  changed_when: false

- name: ensure user is added to vboxusers group
  user:
    name: "{{ virtualbox_username.stdout }}"
    groups: vboxusers
    append: true
    update_password: on_create
  become: true

##https://ratil.life/unattended-install-virtualbox-ext-pack/
- name: set debconf selection for unattended virtualbox-ext-pack install
  shell: "echo virtualbox-ext-pack virtualbox-ext-pack/license select true | debconf-set-selections"
  changed_when: false
  become: true

- name: install virtualbox extension pack
  apt:
    name: virtualbox-ext-pack
    state: present
  become: true
